// swift-tools-version: 5.9
//
// Hand-written manifest for the shared Convos Swift packages. The target
// sources under ConvosMetrics/ and ConvosBridge/ are GENERATED by the metrics
// and bridge Gradle builds respectively — never edit those by hand — but this
// manifest itself is maintained manually.
// Package name stays "ConvosMetrics" so existing SPM pins keep resolving.

import PackageDescription

let package = Package(
    name: "ConvosMetrics",
    platforms: [
        .iOS(.v14),
        .macOS(.v11),
    ],
    products: [
        .library(name: "ConvosMetrics", targets: ["ConvosMetrics"]),
        .library(name: "ConvosBridge", targets: ["ConvosBridge"]),
    ],
    targets: [
        .target(name: "ConvosMetrics", path: "ConvosMetrics/Sources/ConvosMetrics"),
        .target(
            name: "ConvosBridge",
            path: "ConvosBridge/Sources/ConvosBridge",
            // The generated convos.js, injected into the WKWebView as a
            // document-start user script. Access via Bundle.module.
            resources: [.copy("Resources/convos.js")]
        ),
    ]
)
