package org.convos.bridge.codegen.js

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import org.convos.bridge.codegen.model.BridgeModel
import org.convos.bridge.codegen.model.FunctionDescriptor
import org.convos.bridge.codegen.model.PluginDescriptor
import org.convos.bridge.codegen.model.TypeKind
import org.convos.bridge.codegen.model.TypeRef

/**
 * Emits `convos.js`: a dependency-free script that installs `window.convos`, a
 * `Convos` instance with one JSDoc-typed async method per bridge function. It
 * hides the platform transports (Android `window.ConvosNative`, iOS
 * `window.webkit.messageHandlers.convos`) behind promise-correlated envelopes.
 */
class ConvosJsGenerator(
    private val codeGenerator: CodeGenerator,
) {
    fun generate(model: BridgeModel) {
        val script = generateScript(model)
        // The committed web mirror (synced to <repoRoot>/web/convos.js).
        writeJs(WEB_PACKAGE, script)
        // A copy bundled as a resource of the ConvosBridge Swift package so the
        // native runtime can inject it as a document-start user script. Landed
        // under the Swift source tree so syncBridgeSwiftPackage mirrors it into
        // ConvosBridge/Sources/ConvosBridge/Resources/convos.js.
        writeJs(SWIFT_RESOURCES_PACKAGE, script)
    }

    private fun writeJs(packageName: String, script: String) {
        codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true),
            packageName = packageName,
            fileName = "convos",
            extensionName = "js",
        ).bufferedWriter().use { it.write(script) }
    }

    private fun generateScript(model: BridgeModel): String = buildString {
        appendLine("// AUTOGENERATED by the convos bridge codegen processor. Do not edit.")
        appendLine("// Exposes window.convos: a typed facade over the native Convos web bridge.")
        appendLine()
        appendTypedefs(model)
        appendLine("(function () {")
        appendLine(RUNTIME_PRELUDE.trimEnd('\n'))
        for (plugin in model.plugins) {
            appendLine()
            appendLine("  // ── ${plugin.pluginName} ".padEnd(64, '─'))
            for (function in plugin.functions) {
                appendMethod(plugin, function)
            }
        }
        appendLine("}")
        appendLine()
        appendLine("window.convos = new Convos();")
        appendLine("})();")
    }

    private fun StringBuilder.appendTypedefs(model: BridgeModel) {
        if (model.enums.isEmpty() && model.structs.isEmpty()) return
        appendLine("/**")
        for (enum in model.enums) {
            val union = enum.values.joinToString("|") { "\"$it\"" }
            appendLine(" * @typedef {($union)} ${enum.name}")
        }
        for (struct in model.structs) {
            appendLine(" * @typedef {Object} ${struct.name}")
            for (property in struct.properties) {
                appendLine(" * @property {${jsDocType(property.type)}} ${property.name}")
            }
        }
        appendLine(" */")
        appendLine()
    }

    private fun StringBuilder.appendMethod(plugin: PluginDescriptor, function: FunctionDescriptor) {
        val params = function.parameters
        val paramDocs = params.joinToString(" ") { "@param {${jsDocType(it.type)}} ${it.name}" }
        val argumentList = params.joinToString(", ") { it.name }
        val paramsObject = if (params.isEmpty()) "{}" else "{ $argumentList }"
        val wireMethod = "${plugin.pluginName}.${function.name}"

        if (function.isEvent) {
            val payloadType = jsDocType(function.returnType.element!!)
            val doc = "Subscribes to the $wireMethod event. " +
                "@param {function(${payloadType}): void} cb @returns {function(): void} unsubscribe"
            appendLine("  /** $doc */")
            appendLine("  ${function.name}(cb) { return this._subscribe(\"$wireMethod\", cb); }")
        } else if (function.isNotification) {
            val doc = listOf("Fire-and-forget.", paramDocs, "@returns {void}")
                .filter { it.isNotEmpty() }.joinToString(" ")
            appendLine("  /** $doc */")
            appendLine("  ${function.name}($argumentList) { this._notify(\"$wireMethod\", $paramsObject); }")
        } else {
            val returns = "@returns {Promise<${jsDocReturnType(function.returnType)}>}"
            val doc = listOf(paramDocs, returns).filter { it.isNotEmpty() }.joinToString(" ")
            appendLine("  /** $doc */")
            appendLine("  ${function.name}($argumentList) { return this._call(\"$wireMethod\", $paramsObject); }")
        }
    }

    private fun jsDocReturnType(type: TypeRef): String =
        if (type.kind == TypeKind.UNIT) "void" else jsDocType(type)

    private fun jsDocType(type: TypeRef): String {
        val base = when (type.kind) {
            TypeKind.STRING -> "string"
            TypeKind.INT, TypeKind.LONG, TypeKind.DOUBLE, TypeKind.FLOAT -> "number"
            TypeKind.BOOLEAN -> "boolean"
            TypeKind.UNIT -> "void"
            TypeKind.ENUM, TypeKind.STRUCT -> type.name
            TypeKind.LIST -> {
                val element = jsDocType(type.element!!)
                if (element.startsWith("?")) "Array<$element>" else "$element[]"
            }
            // A Flow only ever appears as an event's return type; its element type
            // is what the subscription callback receives.
            TypeKind.FLOW -> jsDocType(type.element!!)
        }
        return if (type.nullable) "?$base" else base
    }

    companion object {
        private const val WEB_PACKAGE = "web"
        private const val SWIFT_RESOURCES_PACKAGE = "swift.Sources.ConvosBridge.Resources"

        private val RUNTIME_PRELUDE = """
class ConvosBridgeError extends Error {
  constructor(code, message) {
    super(message);
    this.name = "ConvosBridgeError";
    this.code = code;
  }
}

class Convos {
  constructor() {
    this._pending = new Map();
    this._listeners = new Map();
    this._nextId = 1;
    if (window.ConvosNative && typeof window.ConvosNative.postMessage === "function") {
      // Android: object injected via addJavascriptInterface.
      this._post = (json) => window.ConvosNative.postMessage(json);
    } else if (window.webkit && window.webkit.messageHandlers &&
               window.webkit.messageHandlers.convos) {
      // iOS: WKScriptMessageHandler named "convos".
      this._post = (json) => window.webkit.messageHandlers.convos.postMessage(json);
    } else {
      this._post = () => {
        throw new ConvosBridgeError("NO_TRANSPORT", "No native Convos bridge found");
      };
    }
  }

  /**
   * Called by the native side with a response envelope. Not part of the
   * public surface.
   * @param {{id: string, ok: boolean, result?: *, error?: {code: string, message: string}}} envelope
   */
  _handleResponse(envelope) {
    const pending = this._pending.get(envelope.id);
    if (!pending) return;
    this._pending.delete(envelope.id);
    if (envelope.ok) {
      pending.resolve(envelope.result === undefined ? null : envelope.result);
    } else {
      const error = envelope.error || { code: "PLUGIN_ERROR", message: "Unknown error" };
      pending.reject(new ConvosBridgeError(error.code, error.message));
    }
  }

  /**
   * Called by the native side with an event envelope. Not part of the public
   * surface.
   * @param {{event: string, params: *}} envelope
   */
  _handleEvent(envelope) {
    const listeners = this._listeners.get(envelope.event);
    if (!listeners) return;
    for (const cb of [...listeners]) {
      try { cb(envelope.params); } catch (_) { /* one bad listener must not stop the rest */ }
    }
  }

  /**
   * Registers a callback for a native event, telling native to start emitting
   * on the first listener. Returns an idempotent unsubscribe function.
   */
  _subscribe(event, cb) {
    let listeners = this._listeners.get(event);
    if (!listeners) {
      listeners = new Set();
      this._listeners.set(event, listeners);
      this._notify("_bridge.subscribe", { event });
    }
    listeners.add(cb);
    return () => {
      const set = this._listeners.get(event);
      if (!set || !set.delete(cb) || set.size > 0) return;
      this._listeners.delete(event);
      this._notify("_bridge.unsubscribe", { event });
    };
  }

  _call(method, params) {
    const id = String(this._nextId++);
    const promise = new Promise((resolve, reject) => {
      this._pending.set(id, { resolve, reject });
    });
    try {
      this._post(JSON.stringify({ id, method, params }));
    } catch (e) {
      this._pending.delete(id);
      return Promise.reject(e);
    }
    return promise;
  }

  _notify(method, params) {
    this._post(JSON.stringify({ id: null, method, params }));
  }

  /** Tells the native side the page's JavaScript is initialized. @returns {void} */
  onReady() { this._notify("_bridge.ready", {}); }
"""
    }
}
