plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

kotlin {
    jvmToolchain(17)
}

android {
    namespace = "org.convos.bridge.android"
    compileSdk = 35

    defaultConfig {
        minSdk = 26
    }

    // convos.js is generated by the :plugins KSP build; expose it as a library
    // asset so ConvosWebBridge can inject it and the host app inherits it.
    sourceSets["main"].assets.srcDir(layout.buildDirectory.dir("convosAssets"))
}

dependencies {
    api(project(":runtime"))
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.androidx.webkit)
}

val syncConvosAsset = tasks.register<Sync>("syncConvosAsset") {
    group = "convos"
    description = "Copies the generated convos.js into the runtime-android assets."
    dependsOn(":plugins:kspKotlin")
    from(project(":plugins").layout.buildDirectory.file("generated/ksp/main/resources/web/convos.js"))
    into(layout.buildDirectory.dir("convosAssets"))
}

tasks.named("preBuild") {
    dependsOn(syncConvosAsset)
}
