package org.convos.bridge.runtime

import kotlinx.coroutines.flow.Flow
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.decodeFromJsonElement

/**
 * Routes the methods of one plugin to its implementation. Implementations are
 * generated by the bridge codegen processor — one per `@BridgePlugin` interface.
 */
interface PluginHandler {
    /** Wire name of the plugin, e.g. `membership` for `MembershipPlugin`. */
    val pluginName: String

    /**
     * Invokes [method] with [params] and returns the JSON-encoded result
     * ([JsonNull] for `Unit`). Throws [BridgeMethodNotFoundException] for an
     * unknown method and [BridgeInvalidParamsException] for undecodable params.
     */
    suspend fun handle(method: String, params: JsonObject): JsonElement

    /**
     * Returns the flow of JSON-encoded payloads for the named event function
     * (a `Flow<T>`-returning method on the plugin interface), or null if this
     * plugin exposes no such event. Collected by [BridgeDispatcher] while the
     * page has a subscription open.
     */
    fun events(event: String): Flow<JsonElement>? = null
}

class BridgeMethodNotFoundException(pluginName: String, method: String) :
    Exception("Method not found: $pluginName.$method")

class BridgeInvalidParamsException(message: String, cause: Throwable? = null) :
    Exception(message, cause)

/**
 * Decodes one named parameter out of a request's `params` object. A missing key
 * decodes as JSON null so nullable parameters may be omitted; a missing or
 * mistyped value for a non-nullable parameter throws [BridgeInvalidParamsException].
 */
inline fun <reified T> JsonObject.decodeParam(name: String): T {
    val element = this[name] ?: JsonNull
    return try {
        bridgeJson.decodeFromJsonElement<T>(element)
    } catch (e: Exception) {
        throw BridgeInvalidParamsException("Invalid value for parameter '$name'", e)
    }
}
