// AUTOGENERATED by the convos bridge codegen processor. Do not edit.

public protocol AppPlugin: AnyObject {
    func markReady()
}

public final class AppPluginDispatcher: BridgePluginDispatcher {
    public let pluginName = "app"
    private let impl: AppPlugin

    public init(_ impl: AppPlugin) {
        self.impl = impl
    }

    public func handle(method: String, params: BridgeParams) async throws -> Any? {
        switch method {
        case "markReady":
            impl.markReady()
            return nil
        default:
            throw BridgeError.methodNotFound(plugin: pluginName, method: method)
        }
    }
}
