// AUTOGENERATED by the convos bridge codegen processor. Do not edit.

public enum AgentState: String, Codable, Sendable {
    case NONE
    case JOINING
    case ACTIVE
}

public struct AgentStatus: Codable, Sendable {
    public let state: AgentState
    public let progress: Double?

    public init(state: AgentState, progress: Double?) {
        self.state = state
        self.progress = progress
    }
}

public struct ThingInfo: Codable, Sendable {
    public let id: String
    public let title: String

    public init(id: String, title: String) {
        self.id = id
        self.title = title
    }
}

public struct WidgetRef: Codable, Sendable {
    public let title: String
    public let description: String

    public init(title: String, description: String) {
        self.title = title
        self.description = description
    }
}

public struct PopupBounds: Codable, Sendable {
    public let x: Double
    public let y: Double
    public let width: Double
    public let height: Double

    public init(x: Double, y: Double, width: Double, height: Double) {
        self.x = x
        self.y = y
        self.width = width
        self.height = height
    }
}
