// AUTOGENERATED by the convos bridge codegen processor. Do not edit.

public protocol ChatPlugin: AnyObject {
    func showMembersList()
    func getAgentStatus() async throws -> AgentStatus
    func requestAgentJoin()
    func onAgentStatusChanged() -> AsyncStream<AgentStatus>
}

public final class ChatPluginDispatcher: BridgePluginDispatcher {
    public let pluginName = "chat"
    private let impl: ChatPlugin

    public init(_ impl: ChatPlugin) {
        self.impl = impl
    }

    public func handle(method: String, params: BridgeParams) async throws -> Any? {
        switch method {
        case "showMembersList":
            impl.showMembersList()
            return nil
        case "getAgentStatus":
            return try BridgeJSON.encodeResult(try await impl.getAgentStatus())
        case "requestAgentJoin":
            impl.requestAgentJoin()
            return nil
        default:
            throw BridgeError.methodNotFound(plugin: pluginName, method: method)
        }
    }

    public func events(_ name: String) -> AsyncStream<Any>? {
        switch name {
        case "onAgentStatusChanged":
            return AsyncStream { continuation in
                let task = Task {
                    for await value in impl.onAgentStatusChanged() {
                        if let encoded = try? BridgeJSON.encodeResult(value) {
                            continuation.yield(encoded)
                        }
                    }
                    continuation.finish()
                }
                continuation.onTermination = { _ in task.cancel() }
            }
        default:
            return nil
        }
    }
}
