// AUTOGENERATED by the convos bridge codegen processor. Do not edit.

public protocol DesktopPlugin: AnyObject {
    func replyToWidget(id: String, widget: WidgetRef)
    func popupWidget(id: String, url: String, bounds: PopupBounds)
}

public final class DesktopPluginDispatcher: BridgePluginDispatcher {
    public let pluginName = "desktop"
    private let impl: DesktopPlugin

    public init(_ impl: DesktopPlugin) {
        self.impl = impl
    }

    public func handle(method: String, params: BridgeParams) async throws -> Any? {
        switch method {
        case "replyToWidget":
            impl.replyToWidget(id: try params.decode("id"), widget: try params.decode("widget"))
            return nil
        case "popupWidget":
            impl.popupWidget(id: try params.decode("id"), url: try params.decode("url"), bounds: try params.decode("bounds"))
            return nil
        default:
            throw BridgeError.methodNotFound(plugin: pluginName, method: method)
        }
    }
}
