// AUTOGENERATED by the convos bridge codegen processor. Do not edit.

public protocol EventsPlugin: AnyObject {
    func trackEvent(name: String)
}

public final class EventsPluginDispatcher: BridgePluginDispatcher {
    public let pluginName = "events"
    private let impl: EventsPlugin

    public init(_ impl: EventsPlugin) {
        self.impl = impl
    }

    public func handle(method: String, params: BridgeParams) async throws -> Any? {
        switch method {
        case "trackEvent":
            impl.trackEvent(name: try params.decode("name"))
            return nil
        default:
            throw BridgeError.methodNotFound(plugin: pluginName, method: method)
        }
    }
}
