// AUTOGENERATED by the convos bridge codegen processor. Do not edit.

public protocol InvitePlugin: AnyObject {
    func showShareSheet()
    func showScan()
    func showInviteCode()
    func showInvitePicker()
}

public final class InvitePluginDispatcher: BridgePluginDispatcher {
    public let pluginName = "invite"
    private let impl: InvitePlugin

    public init(_ impl: InvitePlugin) {
        self.impl = impl
    }

    public func handle(method: String, params: BridgeParams) async throws -> Any? {
        switch method {
        case "showShareSheet":
            impl.showShareSheet()
            return nil
        case "showScan":
            impl.showScan()
            return nil
        case "showInviteCode":
            impl.showInviteCode()
            return nil
        case "showInvitePicker":
            impl.showInvitePicker()
            return nil
        default:
            throw BridgeError.methodNotFound(plugin: pluginName, method: method)
        }
    }
}
