// AUTOGENERATED by the convos bridge codegen processor. Do not edit.

public protocol ThingsPlugin: AnyObject {
    func showThingsList()
    func getThingsList() async throws -> [ThingInfo]
}

public final class ThingsPluginDispatcher: BridgePluginDispatcher {
    public let pluginName = "things"
    private let impl: ThingsPlugin

    public init(_ impl: ThingsPlugin) {
        self.impl = impl
    }

    public func handle(method: String, params: BridgeParams) async throws -> Any? {
        switch method {
        case "showThingsList":
            impl.showThingsList()
            return nil
        case "getThingsList":
            return try BridgeJSON.encodeResult(try await impl.getThingsList())
        default:
            throw BridgeError.methodNotFound(plugin: pluginName, method: method)
        }
    }
}
