// AUTOGENERATED by the convos bridge codegen processor. Do not edit.
// Exposes window.convos: a typed facade over the native Convos web bridge.

/**
 * @typedef {("NONE"|"JOINING"|"ACTIVE")} AgentState
 * @typedef {Object} AgentStatus
 * @property {AgentState} state
 * @property {?number} progress
 * @typedef {Object} ThingInfo
 * @property {string} id
 * @property {string} title
 * @typedef {Object} WidgetRef
 * @property {string} title
 * @property {string} description
 * @typedef {Object} PopupBounds
 * @property {number} x
 * @property {number} y
 * @property {number} width
 * @property {number} height
 */

(function () {

class ConvosBridgeError extends Error {
  constructor(code, message) {
    super(message);
    this.name = "ConvosBridgeError";
    this.code = code;
  }
}

class Convos {
  constructor() {
    this._pending = new Map();
    this._listeners = new Map();
    this._nextId = 1;
    if (window.ConvosNative && typeof window.ConvosNative.postMessage === "function") {
      // Android: object injected via addJavascriptInterface.
      this._post = (json) => window.ConvosNative.postMessage(json);
    } else if (window.webkit && window.webkit.messageHandlers &&
               window.webkit.messageHandlers.convos) {
      // iOS: WKScriptMessageHandler named "convos".
      this._post = (json) => window.webkit.messageHandlers.convos.postMessage(json);
    } else {
      this._post = () => {
        throw new ConvosBridgeError("NO_TRANSPORT", "No native Convos bridge found");
      };
    }
  }

  /**
   * Called by the native side with a response envelope. Not part of the
   * public surface.
   * @param {{id: string, ok: boolean, result?: *, error?: {code: string, message: string}}} envelope
   */
  _handleResponse(envelope) {
    const pending = this._pending.get(envelope.id);
    if (!pending) return;
    this._pending.delete(envelope.id);
    if (envelope.ok) {
      pending.resolve(envelope.result === undefined ? null : envelope.result);
    } else {
      const error = envelope.error || { code: "PLUGIN_ERROR", message: "Unknown error" };
      pending.reject(new ConvosBridgeError(error.code, error.message));
    }
  }

  /**
   * Called by the native side with an event envelope. Not part of the public
   * surface.
   * @param {{event: string, params: *}} envelope
   */
  _handleEvent(envelope) {
    const listeners = this._listeners.get(envelope.event);
    if (!listeners) return;
    for (const cb of [...listeners]) {
      try { cb(envelope.params); } catch (_) { /* one bad listener must not stop the rest */ }
    }
  }

  /**
   * Registers a callback for a native event, telling native to start emitting
   * on the first listener. Returns an idempotent unsubscribe function.
   */
  _subscribe(event, cb) {
    let listeners = this._listeners.get(event);
    if (!listeners) {
      listeners = new Set();
      this._listeners.set(event, listeners);
      this._notify("_bridge.subscribe", { event });
    }
    listeners.add(cb);
    return () => {
      const set = this._listeners.get(event);
      if (!set || !set.delete(cb) || set.size > 0) return;
      this._listeners.delete(event);
      this._notify("_bridge.unsubscribe", { event });
    };
  }

  _call(method, params) {
    const id = String(this._nextId++);
    const promise = new Promise((resolve, reject) => {
      this._pending.set(id, { resolve, reject });
    });
    try {
      this._post(JSON.stringify({ id, method, params }));
    } catch (e) {
      this._pending.delete(id);
      return Promise.reject(e);
    }
    return promise;
  }

  _notify(method, params) {
    this._post(JSON.stringify({ id: null, method, params }));
  }

  /** Tells the native side the page's JavaScript is initialized. @returns {void} */
  onReady() { this._notify("_bridge.ready", {}); }

  // ── app ────────────────────────────────────────────────────
  /** Fire-and-forget. @returns {void} */
  markReady() { this._notify("app.markReady", {}); }

  // ── chat ───────────────────────────────────────────────────
  /** Fire-and-forget. @returns {void} */
  showMembersList() { this._notify("chat.showMembersList", {}); }
  /** @returns {Promise<AgentStatus>} */
  getAgentStatus() { return this._call("chat.getAgentStatus", {}); }
  /** Fire-and-forget. @returns {void} */
  requestAgentJoin() { this._notify("chat.requestAgentJoin", {}); }
  /** Subscribes to the chat.onAgentStatusChanged event. @param {function(AgentStatus): void} cb @returns {function(): void} unsubscribe */
  onAgentStatusChanged(cb) { return this._subscribe("chat.onAgentStatusChanged", cb); }

  // ── desktop ────────────────────────────────────────────────
  /** Fire-and-forget. @param {string} id @param {WidgetRef} widget @returns {void} */
  replyToWidget(id, widget) { this._notify("desktop.replyToWidget", { id, widget }); }
  /** Fire-and-forget. @param {string} id @param {string} url @param {PopupBounds} bounds @returns {void} */
  popupWidget(id, url, bounds) { this._notify("desktop.popupWidget", { id, url, bounds }); }

  // ── events ─────────────────────────────────────────────────
  /** Fire-and-forget. @param {string} name @returns {void} */
  trackEvent(name) { this._notify("events.trackEvent", { name }); }

  // ── invite ─────────────────────────────────────────────────
  /** Fire-and-forget. @returns {void} */
  showShareSheet() { this._notify("invite.showShareSheet", {}); }
  /** Fire-and-forget. @returns {void} */
  showScan() { this._notify("invite.showScan", {}); }
  /** Fire-and-forget. @returns {void} */
  showInviteCode() { this._notify("invite.showInviteCode", {}); }
  /** Fire-and-forget. @returns {void} */
  showInvitePicker() { this._notify("invite.showInvitePicker", {}); }

  // ── things ─────────────────────────────────────────────────
  /** Fire-and-forget. @returns {void} */
  showThingsList() { this._notify("things.showThingsList", {}); }
  /** @returns {Promise<ThingInfo[]>} */
  getThingsList() { return this._call("things.getThingsList", {}); }
}

window.convos = new Convos();
})();
